apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mern-ui
    spec:
      containers:
        - name: mern-ui
          image: rahmafeidi/ui
          ports:
            - containerPort: 3000
              name: http-port
  selector:
    matchLabels:
      app: mern-ui
